name: Maven GitHub Actions Sample

on: [push]

jobs:
  compile:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}
      - name: Compile the Project
#        if other directory is used
#        working-directory: github-actions-java-maven
        run: mvn clean compile

  build:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
      - name: Build and test project
#        working-directory: sample-giithub-action
        run: mvn package assembly:single
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample-giithub-action.jar
          path: target/sample-giithub-action.jar
#          if other directory is used
#          path: sample-giithub-action/target/sample-giithub-action.jar
