name: Maven GitHub Actions Sample

on: [push]

jobs:
  compile:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}
      - name: Compile the Project
#        if other directory is used
#        working-directory: sample-giithub-action
        run: mvn clean compile

  build:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
      - name: Build and test project
#        working-directory: sample-giithub-action
        run: mvn package assembly:single
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact.jar
          path: target/Simple-1.0-SNAPSHOT.jar
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
#          if other directory is used
#          path: sample-giithub-action/target/sample-giithub-action.jar

  publish:
    runs-on: ubuntu-20.04
    needs: build
    name: Publish binary to GitHub Releases
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        run: cargo build --release
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: target/Simple-1.0-SNAPSHOT.jar
         asset_name: Simple-1.0-SNAPSHOT.jar
         tag: ${{ github.ref }}
         overwrite: true
         body: "This is my release first"
